FROM ubuntu

RUN apt-get update -y

RUN apt-get install socat -y

RUN touch /tmp/test

EXPOSE 9001

RUN  echo "Sample file" >/tmp/test

CMD socat -t 100000000 TCP4-LISTEN:9001,fork 'SYSTEM:cat /tmp/test'
